// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/pluginkv"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PluginKVUpdate is the builder for updating PluginKV entities.
type PluginKVUpdate struct {
	config
	hooks    []Hook
	mutation *PluginKVMutation
}

// Where appends a list predicates to the PluginKVUpdate builder.
func (_u *PluginKVUpdate) Where(ps ...predicate.PluginKV) *PluginKVUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPluginID sets the "plugin_id" field.
func (_u *PluginKVUpdate) SetPluginID(v string) *PluginKVUpdate {
	_u.mutation.SetPluginID(v)
	return _u
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (_u *PluginKVUpdate) SetNillablePluginID(v *string) *PluginKVUpdate {
	if v != nil {
		_u.SetPluginID(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *PluginKVUpdate) SetKey(v string) *PluginKVUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *PluginKVUpdate) SetNillableKey(v *string) *PluginKVUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *PluginKVUpdate) SetValue(v string) *PluginKVUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *PluginKVUpdate) SetNillableValue(v *string) *PluginKVUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PluginKVUpdate) SetUpdatedAt(v time.Time) *PluginKVUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PluginKVMutation object of the builder.
func (_u *PluginKVUpdate) Mutation() *PluginKVMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PluginKVUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginKVUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PluginKVUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginKVUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PluginKVUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pluginkv.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PluginKVUpdate) check() error {
	if v, ok := _u.mutation.PluginID(); ok {
		if err := pluginkv.PluginIDValidator(v); err != nil {
			return &ValidationError{Name: "plugin_id", err: fmt.Errorf(`ent: validator failed for field "PluginKV.plugin_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Key(); ok {
		if err := pluginkv.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "PluginKV.key": %w`, err)}
		}
	}
	return nil
}

func (_u *PluginKVUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pluginkv.Table, pluginkv.Columns, sqlgraph.NewFieldSpec(pluginkv.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PluginID(); ok {
		_spec.SetField(pluginkv.FieldPluginID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(pluginkv.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(pluginkv.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pluginkv.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pluginkv.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PluginKVUpdateOne is the builder for updating a single PluginKV entity.
type PluginKVUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PluginKVMutation
}

// SetPluginID sets the "plugin_id" field.
func (_u *PluginKVUpdateOne) SetPluginID(v string) *PluginKVUpdateOne {
	_u.mutation.SetPluginID(v)
	return _u
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (_u *PluginKVUpdateOne) SetNillablePluginID(v *string) *PluginKVUpdateOne {
	if v != nil {
		_u.SetPluginID(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *PluginKVUpdateOne) SetKey(v string) *PluginKVUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *PluginKVUpdateOne) SetNillableKey(v *string) *PluginKVUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *PluginKVUpdateOne) SetValue(v string) *PluginKVUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *PluginKVUpdateOne) SetNillableValue(v *string) *PluginKVUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PluginKVUpdateOne) SetUpdatedAt(v time.Time) *PluginKVUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PluginKVMutation object of the builder.
func (_u *PluginKVUpdateOne) Mutation() *PluginKVMutation {
	return _u.mutation
}

// Where appends a list predicates to the PluginKVUpdate builder.
func (_u *PluginKVUpdateOne) Where(ps ...predicate.PluginKV) *PluginKVUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PluginKVUpdateOne) Select(field string, fields ...string) *PluginKVUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PluginKV entity.
func (_u *PluginKVUpdateOne) Save(ctx context.Context) (*PluginKV, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginKVUpdateOne) SaveX(ctx context.Context) *PluginKV {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PluginKVUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginKVUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PluginKVUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pluginkv.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PluginKVUpdateOne) check() error {
	if v, ok := _u.mutation.PluginID(); ok {
		if err := pluginkv.PluginIDValidator(v); err != nil {
			return &ValidationError{Name: "plugin_id", err: fmt.Errorf(`ent: validator failed for field "PluginKV.plugin_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Key(); ok {
		if err := pluginkv.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "PluginKV.key": %w`, err)}
		}
	}
	return nil
}

func (_u *PluginKVUpdateOne) sqlSave(ctx context.Context) (_node *PluginKV, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pluginkv.Table, pluginkv.Columns, sqlgraph.NewFieldSpec(pluginkv.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PluginKV.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pluginkv.FieldID)
		for _, f := range fields {
			if !pluginkv.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pluginkv.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PluginID(); ok {
		_spec.SetField(pluginkv.FieldPluginID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(pluginkv.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(pluginkv.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pluginkv.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PluginKV{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pluginkv.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
