// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/pluginstate"
)

// PluginStateCreate is the builder for creating a PluginState entity.
type PluginStateCreate struct {
	config
	mutation *PluginStateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetEnabled sets the "enabled" field.
func (_c *PluginStateCreate) SetEnabled(v bool) *PluginStateCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *PluginStateCreate) SetNillableEnabled(v *bool) *PluginStateCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *PluginStateCreate) SetUpdatedBy(v string) *PluginStateCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *PluginStateCreate) SetNillableUpdatedBy(v *string) *PluginStateCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PluginStateCreate) SetUpdatedAt(v time.Time) *PluginStateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PluginStateCreate) SetNillableUpdatedAt(v *time.Time) *PluginStateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PluginStateCreate) SetID(v string) *PluginStateCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PluginStateMutation object of the builder.
func (_c *PluginStateCreate) Mutation() *PluginStateMutation {
	return _c.mutation
}

// Save creates the PluginState in the database.
func (_c *PluginStateCreate) Save(ctx context.Context) (*PluginState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PluginStateCreate) SaveX(ctx context.Context) *PluginState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PluginStateCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := pluginstate.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.UpdatedBy(); !ok {
		v := pluginstate.DefaultUpdatedBy
		_c.mutation.SetUpdatedBy(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := pluginstate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PluginStateCreate) check() error {
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "PluginState.enabled"`)}
	}
	if _, ok := _c.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent: missing required field "PluginState.updated_by"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PluginState.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := pluginstate.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "PluginState.id": %w`, err)}
		}
	}
	return nil
}

func (_c *PluginStateCreate) sqlSave(ctx context.Context) (*PluginState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected PluginState.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PluginStateCreate) createSpec() (*PluginState, *sqlgraph.CreateSpec) {
	var (
		_node = &PluginState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pluginstate.Table, sqlgraph.NewFieldSpec(pluginstate.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(pluginstate.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(pluginstate.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(pluginstate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PluginState.Create().
//		SetEnabled(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PluginStateUpsert) {
//			SetEnabled(v+v).
//		}).
//		Exec(ctx)
func (_c *PluginStateCreate) OnConflict(opts ...sql.ConflictOption) *PluginStateUpsertOne {
	_c.conflict = opts
	return &PluginStateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PluginState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PluginStateCreate) OnConflictColumns(columns ...string) *PluginStateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PluginStateUpsertOne{
		create: _c,
	}
}

type (
	// PluginStateUpsertOne is the builder for "upsert"-ing
	//  one PluginState node.
	PluginStateUpsertOne struct {
		create *PluginStateCreate
	}

	// PluginStateUpsert is the "OnConflict" setter.
	PluginStateUpsert struct {
		*sql.UpdateSet
	}
)

// SetEnabled sets the "enabled" field.
func (u *PluginStateUpsert) SetEnabled(v bool) *PluginStateUpsert {
	u.Set(pluginstate.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PluginStateUpsert) UpdateEnabled() *PluginStateUpsert {
	u.SetExcluded(pluginstate.FieldEnabled)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *PluginStateUpsert) SetUpdatedBy(v string) *PluginStateUpsert {
	u.Set(pluginstate.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *PluginStateUpsert) UpdateUpdatedBy() *PluginStateUpsert {
	u.SetExcluded(pluginstate.FieldUpdatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PluginStateUpsert) SetUpdatedAt(v time.Time) *PluginStateUpsert {
	u.Set(pluginstate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PluginStateUpsert) UpdateUpdatedAt() *PluginStateUpsert {
	u.SetExcluded(pluginstate.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PluginState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(pluginstate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PluginStateUpsertOne) UpdateNewValues() *PluginStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(pluginstate.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PluginState.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PluginStateUpsertOne) Ignore() *PluginStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PluginStateUpsertOne) DoNothing() *PluginStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PluginStateCreate.OnConflict
// documentation for more info.
func (u *PluginStateUpsertOne) Update(set func(*PluginStateUpsert)) *PluginStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PluginStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetEnabled sets the "enabled" field.
func (u *PluginStateUpsertOne) SetEnabled(v bool) *PluginStateUpsertOne {
	return u.Update(func(s *PluginStateUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PluginStateUpsertOne) UpdateEnabled() *PluginStateUpsertOne {
	return u.Update(func(s *PluginStateUpsert) {
		s.UpdateEnabled()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *PluginStateUpsertOne) SetUpdatedBy(v string) *PluginStateUpsertOne {
	return u.Update(func(s *PluginStateUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *PluginStateUpsertOne) UpdateUpdatedBy() *PluginStateUpsertOne {
	return u.Update(func(s *PluginStateUpsert) {
		s.UpdateUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PluginStateUpsertOne) SetUpdatedAt(v time.Time) *PluginStateUpsertOne {
	return u.Update(func(s *PluginStateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PluginStateUpsertOne) UpdateUpdatedAt() *PluginStateUpsertOne {
	return u.Update(func(s *PluginStateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PluginStateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PluginStateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PluginStateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PluginStateUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PluginStateUpsertOne.ID is not supported by MySQL driver. Use PluginStateUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PluginStateUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PluginStateCreateBulk is the builder for creating many PluginState entities in bulk.
type PluginStateCreateBulk struct {
	config
	err      error
	builders []*PluginStateCreate
	conflict []sql.ConflictOption
}

// Save creates the PluginState entities in the database.
func (_c *PluginStateCreateBulk) Save(ctx context.Context) ([]*PluginState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PluginState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PluginStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PluginStateCreateBulk) SaveX(ctx context.Context) []*PluginState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PluginState.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PluginStateUpsert) {
//			SetEnabled(v+v).
//		}).
//		Exec(ctx)
func (_c *PluginStateCreateBulk) OnConflict(opts ...sql.ConflictOption) *PluginStateUpsertBulk {
	_c.conflict = opts
	return &PluginStateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PluginState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PluginStateCreateBulk) OnConflictColumns(columns ...string) *PluginStateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PluginStateUpsertBulk{
		create: _c,
	}
}

// PluginStateUpsertBulk is the builder for "upsert"-ing
// a bulk of PluginState nodes.
type PluginStateUpsertBulk struct {
	create *PluginStateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PluginState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(pluginstate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PluginStateUpsertBulk) UpdateNewValues() *PluginStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(pluginstate.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PluginState.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PluginStateUpsertBulk) Ignore() *PluginStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PluginStateUpsertBulk) DoNothing() *PluginStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PluginStateCreateBulk.OnConflict
// documentation for more info.
func (u *PluginStateUpsertBulk) Update(set func(*PluginStateUpsert)) *PluginStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PluginStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetEnabled sets the "enabled" field.
func (u *PluginStateUpsertBulk) SetEnabled(v bool) *PluginStateUpsertBulk {
	return u.Update(func(s *PluginStateUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PluginStateUpsertBulk) UpdateEnabled() *PluginStateUpsertBulk {
	return u.Update(func(s *PluginStateUpsert) {
		s.UpdateEnabled()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *PluginStateUpsertBulk) SetUpdatedBy(v string) *PluginStateUpsertBulk {
	return u.Update(func(s *PluginStateUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *PluginStateUpsertBulk) UpdateUpdatedBy() *PluginStateUpsertBulk {
	return u.Update(func(s *PluginStateUpsert) {
		s.UpdateUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PluginStateUpsertBulk) SetUpdatedAt(v time.Time) *PluginStateUpsertBulk {
	return u.Update(func(s *PluginStateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PluginStateUpsertBulk) UpdateUpdatedAt() *PluginStateUpsertBulk {
	return u.Update(func(s *PluginStateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PluginStateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PluginStateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PluginStateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PluginStateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
