// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/plugininstallation"
)

// PluginInstallationCreate is the builder for creating a PluginInstallation entity.
type PluginInstallationCreate struct {
	config
	mutation *PluginInstallationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetVersion sets the "version" field.
func (_c *PluginInstallationCreate) SetVersion(v string) *PluginInstallationCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetManifest sets the "manifest" field.
func (_c *PluginInstallationCreate) SetManifest(v json.RawMessage) *PluginInstallationCreate {
	_c.mutation.SetManifest(v)
	return _c
}

// SetInstallPath sets the "install_path" field.
func (_c *PluginInstallationCreate) SetInstallPath(v string) *PluginInstallationCreate {
	_c.mutation.SetInstallPath(v)
	return _c
}

// SetChecksum sets the "checksum" field.
func (_c *PluginInstallationCreate) SetChecksum(v string) *PluginInstallationCreate {
	_c.mutation.SetChecksum(v)
	return _c
}

// SetConfig sets the "config" field.
func (_c *PluginInstallationCreate) SetConfig(v json.RawMessage) *PluginInstallationCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetInstalledBy sets the "installed_by" field.
func (_c *PluginInstallationCreate) SetInstalledBy(v string) *PluginInstallationCreate {
	_c.mutation.SetInstalledBy(v)
	return _c
}

// SetNillableInstalledBy sets the "installed_by" field if the given value is not nil.
func (_c *PluginInstallationCreate) SetNillableInstalledBy(v *string) *PluginInstallationCreate {
	if v != nil {
		_c.SetInstalledBy(*v)
	}
	return _c
}

// SetInstalledAt sets the "installed_at" field.
func (_c *PluginInstallationCreate) SetInstalledAt(v time.Time) *PluginInstallationCreate {
	_c.mutation.SetInstalledAt(v)
	return _c
}

// SetNillableInstalledAt sets the "installed_at" field if the given value is not nil.
func (_c *PluginInstallationCreate) SetNillableInstalledAt(v *time.Time) *PluginInstallationCreate {
	if v != nil {
		_c.SetInstalledAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PluginInstallationCreate) SetUpdatedAt(v time.Time) *PluginInstallationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PluginInstallationCreate) SetNillableUpdatedAt(v *time.Time) *PluginInstallationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PluginInstallationCreate) SetID(v string) *PluginInstallationCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PluginInstallationMutation object of the builder.
func (_c *PluginInstallationCreate) Mutation() *PluginInstallationMutation {
	return _c.mutation
}

// Save creates the PluginInstallation in the database.
func (_c *PluginInstallationCreate) Save(ctx context.Context) (*PluginInstallation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PluginInstallationCreate) SaveX(ctx context.Context) *PluginInstallation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginInstallationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginInstallationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PluginInstallationCreate) defaults() {
	if _, ok := _c.mutation.InstalledBy(); !ok {
		v := plugininstallation.DefaultInstalledBy
		_c.mutation.SetInstalledBy(v)
	}
	if _, ok := _c.mutation.InstalledAt(); !ok {
		v := plugininstallation.DefaultInstalledAt()
		_c.mutation.SetInstalledAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := plugininstallation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PluginInstallationCreate) check() error {
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "PluginInstallation.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := plugininstallation.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "PluginInstallation.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Manifest(); !ok {
		return &ValidationError{Name: "manifest", err: errors.New(`ent: missing required field "PluginInstallation.manifest"`)}
	}
	if _, ok := _c.mutation.InstallPath(); !ok {
		return &ValidationError{Name: "install_path", err: errors.New(`ent: missing required field "PluginInstallation.install_path"`)}
	}
	if v, ok := _c.mutation.InstallPath(); ok {
		if err := plugininstallation.InstallPathValidator(v); err != nil {
			return &ValidationError{Name: "install_path", err: fmt.Errorf(`ent: validator failed for field "PluginInstallation.install_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Checksum(); !ok {
		return &ValidationError{Name: "checksum", err: errors.New(`ent: missing required field "PluginInstallation.checksum"`)}
	}
	if v, ok := _c.mutation.Checksum(); ok {
		if err := plugininstallation.ChecksumValidator(v); err != nil {
			return &ValidationError{Name: "checksum", err: fmt.Errorf(`ent: validator failed for field "PluginInstallation.checksum": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InstalledBy(); !ok {
		return &ValidationError{Name: "installed_by", err: errors.New(`ent: missing required field "PluginInstallation.installed_by"`)}
	}
	if _, ok := _c.mutation.InstalledAt(); !ok {
		return &ValidationError{Name: "installed_at", err: errors.New(`ent: missing required field "PluginInstallation.installed_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PluginInstallation.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := plugininstallation.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "PluginInstallation.id": %w`, err)}
		}
	}
	return nil
}

func (_c *PluginInstallationCreate) sqlSave(ctx context.Context) (*PluginInstallation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected PluginInstallation.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PluginInstallationCreate) createSpec() (*PluginInstallation, *sqlgraph.CreateSpec) {
	var (
		_node = &PluginInstallation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(plugininstallation.Table, sqlgraph.NewFieldSpec(plugininstallation.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(plugininstallation.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Manifest(); ok {
		_spec.SetField(plugininstallation.FieldManifest, field.TypeJSON, value)
		_node.Manifest = value
	}
	if value, ok := _c.mutation.InstallPath(); ok {
		_spec.SetField(plugininstallation.FieldInstallPath, field.TypeString, value)
		_node.InstallPath = value
	}
	if value, ok := _c.mutation.Checksum(); ok {
		_spec.SetField(plugininstallation.FieldChecksum, field.TypeString, value)
		_node.Checksum = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(plugininstallation.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.InstalledBy(); ok {
		_spec.SetField(plugininstallation.FieldInstalledBy, field.TypeString, value)
		_node.InstalledBy = value
	}
	if value, ok := _c.mutation.InstalledAt(); ok {
		_spec.SetField(plugininstallation.FieldInstalledAt, field.TypeTime, value)
		_node.InstalledAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(plugininstallation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PluginInstallation.Create().
//		SetVersion(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PluginInstallationUpsert) {
//			SetVersion(v+v).
//		}).
//		Exec(ctx)
func (_c *PluginInstallationCreate) OnConflict(opts ...sql.ConflictOption) *PluginInstallationUpsertOne {
	_c.conflict = opts
	return &PluginInstallationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PluginInstallation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PluginInstallationCreate) OnConflictColumns(columns ...string) *PluginInstallationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PluginInstallationUpsertOne{
		create: _c,
	}
}

type (
	// PluginInstallationUpsertOne is the builder for "upsert"-ing
	//  one PluginInstallation node.
	PluginInstallationUpsertOne struct {
		create *PluginInstallationCreate
	}

	// PluginInstallationUpsert is the "OnConflict" setter.
	PluginInstallationUpsert struct {
		*sql.UpdateSet
	}
)

// SetVersion sets the "version" field.
func (u *PluginInstallationUpsert) SetVersion(v string) *PluginInstallationUpsert {
	u.Set(plugininstallation.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *PluginInstallationUpsert) UpdateVersion() *PluginInstallationUpsert {
	u.SetExcluded(plugininstallation.FieldVersion)
	return u
}

// SetManifest sets the "manifest" field.
func (u *PluginInstallationUpsert) SetManifest(v json.RawMessage) *PluginInstallationUpsert {
	u.Set(plugininstallation.FieldManifest, v)
	return u
}

// UpdateManifest sets the "manifest" field to the value that was provided on create.
func (u *PluginInstallationUpsert) UpdateManifest() *PluginInstallationUpsert {
	u.SetExcluded(plugininstallation.FieldManifest)
	return u
}

// SetInstallPath sets the "install_path" field.
func (u *PluginInstallationUpsert) SetInstallPath(v string) *PluginInstallationUpsert {
	u.Set(plugininstallation.FieldInstallPath, v)
	return u
}

// UpdateInstallPath sets the "install_path" field to the value that was provided on create.
func (u *PluginInstallationUpsert) UpdateInstallPath() *PluginInstallationUpsert {
	u.SetExcluded(plugininstallation.FieldInstallPath)
	return u
}

// SetChecksum sets the "checksum" field.
func (u *PluginInstallationUpsert) SetChecksum(v string) *PluginInstallationUpsert {
	u.Set(plugininstallation.FieldChecksum, v)
	return u
}

// UpdateChecksum sets the "checksum" field to the value that was provided on create.
func (u *PluginInstallationUpsert) UpdateChecksum() *PluginInstallationUpsert {
	u.SetExcluded(plugininstallation.FieldChecksum)
	return u
}

// SetConfig sets the "config" field.
func (u *PluginInstallationUpsert) SetConfig(v json.RawMessage) *PluginInstallationUpsert {
	u.Set(plugininstallation.FieldConfig, v)
	return u
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *PluginInstallationUpsert) UpdateConfig() *PluginInstallationUpsert {
	u.SetExcluded(plugininstallation.FieldConfig)
	return u
}

// ClearConfig clears the value of the "config" field.
func (u *PluginInstallationUpsert) ClearConfig() *PluginInstallationUpsert {
	u.SetNull(plugininstallation.FieldConfig)
	return u
}

// SetInstalledBy sets the "installed_by" field.
func (u *PluginInstallationUpsert) SetInstalledBy(v string) *PluginInstallationUpsert {
	u.Set(plugininstallation.FieldInstalledBy, v)
	return u
}

// UpdateInstalledBy sets the "installed_by" field to the value that was provided on create.
func (u *PluginInstallationUpsert) UpdateInstalledBy() *PluginInstallationUpsert {
	u.SetExcluded(plugininstallation.FieldInstalledBy)
	return u
}

// SetInstalledAt sets the "installed_at" field.
func (u *PluginInstallationUpsert) SetInstalledAt(v time.Time) *PluginInstallationUpsert {
	u.Set(plugininstallation.FieldInstalledAt, v)
	return u
}

// UpdateInstalledAt sets the "installed_at" field to the value that was provided on create.
func (u *PluginInstallationUpsert) UpdateInstalledAt() *PluginInstallationUpsert {
	u.SetExcluded(plugininstallation.FieldInstalledAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PluginInstallationUpsert) SetUpdatedAt(v time.Time) *PluginInstallationUpsert {
	u.Set(plugininstallation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PluginInstallationUpsert) UpdateUpdatedAt() *PluginInstallationUpsert {
	u.SetExcluded(plugininstallation.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PluginInstallation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(plugininstallation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PluginInstallationUpsertOne) UpdateNewValues() *PluginInstallationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(plugininstallation.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PluginInstallation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PluginInstallationUpsertOne) Ignore() *PluginInstallationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PluginInstallationUpsertOne) DoNothing() *PluginInstallationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PluginInstallationCreate.OnConflict
// documentation for more info.
func (u *PluginInstallationUpsertOne) Update(set func(*PluginInstallationUpsert)) *PluginInstallationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PluginInstallationUpsert{UpdateSet: update})
	}))
	return u
}

// SetVersion sets the "version" field.
func (u *PluginInstallationUpsertOne) SetVersion(v string) *PluginInstallationUpsertOne {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *PluginInstallationUpsertOne) UpdateVersion() *PluginInstallationUpsertOne {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.UpdateVersion()
	})
}

// SetManifest sets the "manifest" field.
func (u *PluginInstallationUpsertOne) SetManifest(v json.RawMessage) *PluginInstallationUpsertOne {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.SetManifest(v)
	})
}

// UpdateManifest sets the "manifest" field to the value that was provided on create.
func (u *PluginInstallationUpsertOne) UpdateManifest() *PluginInstallationUpsertOne {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.UpdateManifest()
	})
}

// SetInstallPath sets the "install_path" field.
func (u *PluginInstallationUpsertOne) SetInstallPath(v string) *PluginInstallationUpsertOne {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.SetInstallPath(v)
	})
}

// UpdateInstallPath sets the "install_path" field to the value that was provided on create.
func (u *PluginInstallationUpsertOne) UpdateInstallPath() *PluginInstallationUpsertOne {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.UpdateInstallPath()
	})
}

// SetChecksum sets the "checksum" field.
func (u *PluginInstallationUpsertOne) SetChecksum(v string) *PluginInstallationUpsertOne {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.SetChecksum(v)
	})
}

// UpdateChecksum sets the "checksum" field to the value that was provided on create.
func (u *PluginInstallationUpsertOne) UpdateChecksum() *PluginInstallationUpsertOne {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.UpdateChecksum()
	})
}

// SetConfig sets the "config" field.
func (u *PluginInstallationUpsertOne) SetConfig(v json.RawMessage) *PluginInstallationUpsertOne {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *PluginInstallationUpsertOne) UpdateConfig() *PluginInstallationUpsertOne {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.UpdateConfig()
	})
}

// ClearConfig clears the value of the "config" field.
func (u *PluginInstallationUpsertOne) ClearConfig() *PluginInstallationUpsertOne {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.ClearConfig()
	})
}

// SetInstalledBy sets the "installed_by" field.
func (u *PluginInstallationUpsertOne) SetInstalledBy(v string) *PluginInstallationUpsertOne {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.SetInstalledBy(v)
	})
}

// UpdateInstalledBy sets the "installed_by" field to the value that was provided on create.
func (u *PluginInstallationUpsertOne) UpdateInstalledBy() *PluginInstallationUpsertOne {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.UpdateInstalledBy()
	})
}

// SetInstalledAt sets the "installed_at" field.
func (u *PluginInstallationUpsertOne) SetInstalledAt(v time.Time) *PluginInstallationUpsertOne {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.SetInstalledAt(v)
	})
}

// UpdateInstalledAt sets the "installed_at" field to the value that was provided on create.
func (u *PluginInstallationUpsertOne) UpdateInstalledAt() *PluginInstallationUpsertOne {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.UpdateInstalledAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PluginInstallationUpsertOne) SetUpdatedAt(v time.Time) *PluginInstallationUpsertOne {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PluginInstallationUpsertOne) UpdateUpdatedAt() *PluginInstallationUpsertOne {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PluginInstallationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PluginInstallationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PluginInstallationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PluginInstallationUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PluginInstallationUpsertOne.ID is not supported by MySQL driver. Use PluginInstallationUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PluginInstallationUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PluginInstallationCreateBulk is the builder for creating many PluginInstallation entities in bulk.
type PluginInstallationCreateBulk struct {
	config
	err      error
	builders []*PluginInstallationCreate
	conflict []sql.ConflictOption
}

// Save creates the PluginInstallation entities in the database.
func (_c *PluginInstallationCreateBulk) Save(ctx context.Context) ([]*PluginInstallation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PluginInstallation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PluginInstallationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PluginInstallationCreateBulk) SaveX(ctx context.Context) []*PluginInstallation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginInstallationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginInstallationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PluginInstallation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PluginInstallationUpsert) {
//			SetVersion(v+v).
//		}).
//		Exec(ctx)
func (_c *PluginInstallationCreateBulk) OnConflict(opts ...sql.ConflictOption) *PluginInstallationUpsertBulk {
	_c.conflict = opts
	return &PluginInstallationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PluginInstallation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PluginInstallationCreateBulk) OnConflictColumns(columns ...string) *PluginInstallationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PluginInstallationUpsertBulk{
		create: _c,
	}
}

// PluginInstallationUpsertBulk is the builder for "upsert"-ing
// a bulk of PluginInstallation nodes.
type PluginInstallationUpsertBulk struct {
	create *PluginInstallationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PluginInstallation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(plugininstallation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PluginInstallationUpsertBulk) UpdateNewValues() *PluginInstallationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(plugininstallation.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PluginInstallation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PluginInstallationUpsertBulk) Ignore() *PluginInstallationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PluginInstallationUpsertBulk) DoNothing() *PluginInstallationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PluginInstallationCreateBulk.OnConflict
// documentation for more info.
func (u *PluginInstallationUpsertBulk) Update(set func(*PluginInstallationUpsert)) *PluginInstallationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PluginInstallationUpsert{UpdateSet: update})
	}))
	return u
}

// SetVersion sets the "version" field.
func (u *PluginInstallationUpsertBulk) SetVersion(v string) *PluginInstallationUpsertBulk {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *PluginInstallationUpsertBulk) UpdateVersion() *PluginInstallationUpsertBulk {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.UpdateVersion()
	})
}

// SetManifest sets the "manifest" field.
func (u *PluginInstallationUpsertBulk) SetManifest(v json.RawMessage) *PluginInstallationUpsertBulk {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.SetManifest(v)
	})
}

// UpdateManifest sets the "manifest" field to the value that was provided on create.
func (u *PluginInstallationUpsertBulk) UpdateManifest() *PluginInstallationUpsertBulk {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.UpdateManifest()
	})
}

// SetInstallPath sets the "install_path" field.
func (u *PluginInstallationUpsertBulk) SetInstallPath(v string) *PluginInstallationUpsertBulk {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.SetInstallPath(v)
	})
}

// UpdateInstallPath sets the "install_path" field to the value that was provided on create.
func (u *PluginInstallationUpsertBulk) UpdateInstallPath() *PluginInstallationUpsertBulk {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.UpdateInstallPath()
	})
}

// SetChecksum sets the "checksum" field.
func (u *PluginInstallationUpsertBulk) SetChecksum(v string) *PluginInstallationUpsertBulk {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.SetChecksum(v)
	})
}

// UpdateChecksum sets the "checksum" field to the value that was provided on create.
func (u *PluginInstallationUpsertBulk) UpdateChecksum() *PluginInstallationUpsertBulk {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.UpdateChecksum()
	})
}

// SetConfig sets the "config" field.
func (u *PluginInstallationUpsertBulk) SetConfig(v json.RawMessage) *PluginInstallationUpsertBulk {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *PluginInstallationUpsertBulk) UpdateConfig() *PluginInstallationUpsertBulk {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.UpdateConfig()
	})
}

// ClearConfig clears the value of the "config" field.
func (u *PluginInstallationUpsertBulk) ClearConfig() *PluginInstallationUpsertBulk {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.ClearConfig()
	})
}

// SetInstalledBy sets the "installed_by" field.
func (u *PluginInstallationUpsertBulk) SetInstalledBy(v string) *PluginInstallationUpsertBulk {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.SetInstalledBy(v)
	})
}

// UpdateInstalledBy sets the "installed_by" field to the value that was provided on create.
func (u *PluginInstallationUpsertBulk) UpdateInstalledBy() *PluginInstallationUpsertBulk {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.UpdateInstalledBy()
	})
}

// SetInstalledAt sets the "installed_at" field.
func (u *PluginInstallationUpsertBulk) SetInstalledAt(v time.Time) *PluginInstallationUpsertBulk {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.SetInstalledAt(v)
	})
}

// UpdateInstalledAt sets the "installed_at" field to the value that was provided on create.
func (u *PluginInstallationUpsertBulk) UpdateInstalledAt() *PluginInstallationUpsertBulk {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.UpdateInstalledAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PluginInstallationUpsertBulk) SetUpdatedAt(v time.Time) *PluginInstallationUpsertBulk {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PluginInstallationUpsertBulk) UpdateUpdatedAt() *PluginInstallationUpsertBulk {
	return u.Update(func(s *PluginInstallationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PluginInstallationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PluginInstallationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PluginInstallationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PluginInstallationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
