// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/plugininstallation"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PluginInstallationUpdate is the builder for updating PluginInstallation entities.
type PluginInstallationUpdate struct {
	config
	hooks    []Hook
	mutation *PluginInstallationMutation
}

// Where appends a list predicates to the PluginInstallationUpdate builder.
func (_u *PluginInstallationUpdate) Where(ps ...predicate.PluginInstallation) *PluginInstallationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetVersion sets the "version" field.
func (_u *PluginInstallationUpdate) SetVersion(v string) *PluginInstallationUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PluginInstallationUpdate) SetNillableVersion(v *string) *PluginInstallationUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetManifest sets the "manifest" field.
func (_u *PluginInstallationUpdate) SetManifest(v json.RawMessage) *PluginInstallationUpdate {
	_u.mutation.SetManifest(v)
	return _u
}

// AppendManifest appends value to the "manifest" field.
func (_u *PluginInstallationUpdate) AppendManifest(v json.RawMessage) *PluginInstallationUpdate {
	_u.mutation.AppendManifest(v)
	return _u
}

// SetInstallPath sets the "install_path" field.
func (_u *PluginInstallationUpdate) SetInstallPath(v string) *PluginInstallationUpdate {
	_u.mutation.SetInstallPath(v)
	return _u
}

// SetNillableInstallPath sets the "install_path" field if the given value is not nil.
func (_u *PluginInstallationUpdate) SetNillableInstallPath(v *string) *PluginInstallationUpdate {
	if v != nil {
		_u.SetInstallPath(*v)
	}
	return _u
}

// SetChecksum sets the "checksum" field.
func (_u *PluginInstallationUpdate) SetChecksum(v string) *PluginInstallationUpdate {
	_u.mutation.SetChecksum(v)
	return _u
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_u *PluginInstallationUpdate) SetNillableChecksum(v *string) *PluginInstallationUpdate {
	if v != nil {
		_u.SetChecksum(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *PluginInstallationUpdate) SetConfig(v json.RawMessage) *PluginInstallationUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// AppendConfig appends value to the "config" field.
func (_u *PluginInstallationUpdate) AppendConfig(v json.RawMessage) *PluginInstallationUpdate {
	_u.mutation.AppendConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *PluginInstallationUpdate) ClearConfig() *PluginInstallationUpdate {
	_u.mutation.ClearConfig()
	return _u
}

// SetInstalledBy sets the "installed_by" field.
func (_u *PluginInstallationUpdate) SetInstalledBy(v string) *PluginInstallationUpdate {
	_u.mutation.SetInstalledBy(v)
	return _u
}

// SetNillableInstalledBy sets the "installed_by" field if the given value is not nil.
func (_u *PluginInstallationUpdate) SetNillableInstalledBy(v *string) *PluginInstallationUpdate {
	if v != nil {
		_u.SetInstalledBy(*v)
	}
	return _u
}

// SetInstalledAt sets the "installed_at" field.
func (_u *PluginInstallationUpdate) SetInstalledAt(v time.Time) *PluginInstallationUpdate {
	_u.mutation.SetInstalledAt(v)
	return _u
}

// SetNillableInstalledAt sets the "installed_at" field if the given value is not nil.
func (_u *PluginInstallationUpdate) SetNillableInstalledAt(v *time.Time) *PluginInstallationUpdate {
	if v != nil {
		_u.SetInstalledAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PluginInstallationUpdate) SetUpdatedAt(v time.Time) *PluginInstallationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PluginInstallationMutation object of the builder.
func (_u *PluginInstallationUpdate) Mutation() *PluginInstallationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PluginInstallationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginInstallationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PluginInstallationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginInstallationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PluginInstallationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := plugininstallation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PluginInstallationUpdate) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := plugininstallation.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "PluginInstallation.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InstallPath(); ok {
		if err := plugininstallation.InstallPathValidator(v); err != nil {
			return &ValidationError{Name: "install_path", err: fmt.Errorf(`ent: validator failed for field "PluginInstallation.install_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Checksum(); ok {
		if err := plugininstallation.ChecksumValidator(v); err != nil {
			return &ValidationError{Name: "checksum", err: fmt.Errorf(`ent: validator failed for field "PluginInstallation.checksum": %w`, err)}
		}
	}
	return nil
}

func (_u *PluginInstallationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(plugininstallation.Table, plugininstallation.Columns, sqlgraph.NewFieldSpec(plugininstallation.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(plugininstallation.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Manifest(); ok {
		_spec.SetField(plugininstallation.FieldManifest, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedManifest(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, plugininstallation.FieldManifest, value)
		})
	}
	if value, ok := _u.mutation.InstallPath(); ok {
		_spec.SetField(plugininstallation.FieldInstallPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Checksum(); ok {
		_spec.SetField(plugininstallation.FieldChecksum, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(plugininstallation.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedConfig(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, plugininstallation.FieldConfig, value)
		})
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(plugininstallation.FieldConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.InstalledBy(); ok {
		_spec.SetField(plugininstallation.FieldInstalledBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.InstalledAt(); ok {
		_spec.SetField(plugininstallation.FieldInstalledAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(plugininstallation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plugininstallation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PluginInstallationUpdateOne is the builder for updating a single PluginInstallation entity.
type PluginInstallationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PluginInstallationMutation
}

// SetVersion sets the "version" field.
func (_u *PluginInstallationUpdateOne) SetVersion(v string) *PluginInstallationUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PluginInstallationUpdateOne) SetNillableVersion(v *string) *PluginInstallationUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetManifest sets the "manifest" field.
func (_u *PluginInstallationUpdateOne) SetManifest(v json.RawMessage) *PluginInstallationUpdateOne {
	_u.mutation.SetManifest(v)
	return _u
}

// AppendManifest appends value to the "manifest" field.
func (_u *PluginInstallationUpdateOne) AppendManifest(v json.RawMessage) *PluginInstallationUpdateOne {
	_u.mutation.AppendManifest(v)
	return _u
}

// SetInstallPath sets the "install_path" field.
func (_u *PluginInstallationUpdateOne) SetInstallPath(v string) *PluginInstallationUpdateOne {
	_u.mutation.SetInstallPath(v)
	return _u
}

// SetNillableInstallPath sets the "install_path" field if the given value is not nil.
func (_u *PluginInstallationUpdateOne) SetNillableInstallPath(v *string) *PluginInstallationUpdateOne {
	if v != nil {
		_u.SetInstallPath(*v)
	}
	return _u
}

// SetChecksum sets the "checksum" field.
func (_u *PluginInstallationUpdateOne) SetChecksum(v string) *PluginInstallationUpdateOne {
	_u.mutation.SetChecksum(v)
	return _u
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_u *PluginInstallationUpdateOne) SetNillableChecksum(v *string) *PluginInstallationUpdateOne {
	if v != nil {
		_u.SetChecksum(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *PluginInstallationUpdateOne) SetConfig(v json.RawMessage) *PluginInstallationUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// AppendConfig appends value to the "config" field.
func (_u *PluginInstallationUpdateOne) AppendConfig(v json.RawMessage) *PluginInstallationUpdateOne {
	_u.mutation.AppendConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *PluginInstallationUpdateOne) ClearConfig() *PluginInstallationUpdateOne {
	_u.mutation.ClearConfig()
	return _u
}

// SetInstalledBy sets the "installed_by" field.
func (_u *PluginInstallationUpdateOne) SetInstalledBy(v string) *PluginInstallationUpdateOne {
	_u.mutation.SetInstalledBy(v)
	return _u
}

// SetNillableInstalledBy sets the "installed_by" field if the given value is not nil.
func (_u *PluginInstallationUpdateOne) SetNillableInstalledBy(v *string) *PluginInstallationUpdateOne {
	if v != nil {
		_u.SetInstalledBy(*v)
	}
	return _u
}

// SetInstalledAt sets the "installed_at" field.
func (_u *PluginInstallationUpdateOne) SetInstalledAt(v time.Time) *PluginInstallationUpdateOne {
	_u.mutation.SetInstalledAt(v)
	return _u
}

// SetNillableInstalledAt sets the "installed_at" field if the given value is not nil.
func (_u *PluginInstallationUpdateOne) SetNillableInstalledAt(v *time.Time) *PluginInstallationUpdateOne {
	if v != nil {
		_u.SetInstalledAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PluginInstallationUpdateOne) SetUpdatedAt(v time.Time) *PluginInstallationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PluginInstallationMutation object of the builder.
func (_u *PluginInstallationUpdateOne) Mutation() *PluginInstallationMutation {
	return _u.mutation
}

// Where appends a list predicates to the PluginInstallationUpdate builder.
func (_u *PluginInstallationUpdateOne) Where(ps ...predicate.PluginInstallation) *PluginInstallationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PluginInstallationUpdateOne) Select(field string, fields ...string) *PluginInstallationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PluginInstallation entity.
func (_u *PluginInstallationUpdateOne) Save(ctx context.Context) (*PluginInstallation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginInstallationUpdateOne) SaveX(ctx context.Context) *PluginInstallation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PluginInstallationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginInstallationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PluginInstallationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := plugininstallation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PluginInstallationUpdateOne) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := plugininstallation.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "PluginInstallation.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InstallPath(); ok {
		if err := plugininstallation.InstallPathValidator(v); err != nil {
			return &ValidationError{Name: "install_path", err: fmt.Errorf(`ent: validator failed for field "PluginInstallation.install_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Checksum(); ok {
		if err := plugininstallation.ChecksumValidator(v); err != nil {
			return &ValidationError{Name: "checksum", err: fmt.Errorf(`ent: validator failed for field "PluginInstallation.checksum": %w`, err)}
		}
	}
	return nil
}

func (_u *PluginInstallationUpdateOne) sqlSave(ctx context.Context) (_node *PluginInstallation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(plugininstallation.Table, plugininstallation.Columns, sqlgraph.NewFieldSpec(plugininstallation.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PluginInstallation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, plugininstallation.FieldID)
		for _, f := range fields {
			if !plugininstallation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != plugininstallation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(plugininstallation.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Manifest(); ok {
		_spec.SetField(plugininstallation.FieldManifest, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedManifest(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, plugininstallation.FieldManifest, value)
		})
	}
	if value, ok := _u.mutation.InstallPath(); ok {
		_spec.SetField(plugininstallation.FieldInstallPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Checksum(); ok {
		_spec.SetField(plugininstallation.FieldChecksum, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(plugininstallation.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedConfig(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, plugininstallation.FieldConfig, value)
		})
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(plugininstallation.FieldConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.InstalledBy(); ok {
		_spec.SetField(plugininstallation.FieldInstalledBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.InstalledAt(); ok {
		_spec.SetField(plugininstallation.FieldInstalledAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(plugininstallation.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PluginInstallation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plugininstallation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
