// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/plugininstallation"
)

// PluginInstallation is the model entity for the PluginInstallation schema.
type PluginInstallation struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// Manifest holds the value of the "manifest" field.
	Manifest json.RawMessage `json:"manifest,omitempty"`
	// InstallPath holds the value of the "install_path" field.
	InstallPath string `json:"install_path,omitempty"`
	// Checksum holds the value of the "checksum" field.
	Checksum string `json:"checksum,omitempty"`
	// Config holds the value of the "config" field.
	Config json.RawMessage `json:"config,omitempty"`
	// InstalledBy holds the value of the "installed_by" field.
	InstalledBy string `json:"installed_by,omitempty"`
	// InstalledAt holds the value of the "installed_at" field.
	InstalledAt time.Time `json:"installed_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PluginInstallation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case plugininstallation.FieldManifest, plugininstallation.FieldConfig:
			values[i] = new([]byte)
		case plugininstallation.FieldID, plugininstallation.FieldVersion, plugininstallation.FieldInstallPath, plugininstallation.FieldChecksum, plugininstallation.FieldInstalledBy:
			values[i] = new(sql.NullString)
		case plugininstallation.FieldInstalledAt, plugininstallation.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PluginInstallation fields.
func (_m *PluginInstallation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case plugininstallation.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case plugininstallation.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case plugininstallation.FieldManifest:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field manifest", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Manifest); err != nil {
					return fmt.Errorf("unmarshal field manifest: %w", err)
				}
			}
		case plugininstallation.FieldInstallPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field install_path", values[i])
			} else if value.Valid {
				_m.InstallPath = value.String
			}
		case plugininstallation.FieldChecksum:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field checksum", values[i])
			} else if value.Valid {
				_m.Checksum = value.String
			}
		case plugininstallation.FieldConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Config); err != nil {
					return fmt.Errorf("unmarshal field config: %w", err)
				}
			}
		case plugininstallation.FieldInstalledBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field installed_by", values[i])
			} else if value.Valid {
				_m.InstalledBy = value.String
			}
		case plugininstallation.FieldInstalledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field installed_at", values[i])
			} else if value.Valid {
				_m.InstalledAt = value.Time
			}
		case plugininstallation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PluginInstallation.
// This includes values selected through modifiers, order, etc.
func (_m *PluginInstallation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PluginInstallation.
// Note that you need to call PluginInstallation.Unwrap() before calling this method if this PluginInstallation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PluginInstallation) Update() *PluginInstallationUpdateOne {
	return NewPluginInstallationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PluginInstallation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PluginInstallation) Unwrap() *PluginInstallation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PluginInstallation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PluginInstallation) String() string {
	var builder strings.Builder
	builder.WriteString("PluginInstallation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("manifest=")
	builder.WriteString(fmt.Sprintf("%v", _m.Manifest))
	builder.WriteString(", ")
	builder.WriteString("install_path=")
	builder.WriteString(_m.InstallPath)
	builder.WriteString(", ")
	builder.WriteString("checksum=")
	builder.WriteString(_m.Checksum)
	builder.WriteString(", ")
	builder.WriteString("config=")
	builder.WriteString(fmt.Sprintf("%v", _m.Config))
	builder.WriteString(", ")
	builder.WriteString("installed_by=")
	builder.WriteString(_m.InstalledBy)
	builder.WriteString(", ")
	builder.WriteString("installed_at=")
	builder.WriteString(_m.InstalledAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PluginInstallations is a parsable slice of PluginInstallation.
type PluginInstallations []*PluginInstallation
