// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/pluginkv"
)

// PluginKVCreate is the builder for creating a PluginKV entity.
type PluginKVCreate struct {
	config
	mutation *PluginKVMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPluginID sets the "plugin_id" field.
func (_c *PluginKVCreate) SetPluginID(v string) *PluginKVCreate {
	_c.mutation.SetPluginID(v)
	return _c
}

// SetKey sets the "key" field.
func (_c *PluginKVCreate) SetKey(v string) *PluginKVCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *PluginKVCreate) SetValue(v string) *PluginKVCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PluginKVCreate) SetCreatedAt(v time.Time) *PluginKVCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PluginKVCreate) SetNillableCreatedAt(v *time.Time) *PluginKVCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PluginKVCreate) SetUpdatedAt(v time.Time) *PluginKVCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PluginKVCreate) SetNillableUpdatedAt(v *time.Time) *PluginKVCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the PluginKVMutation object of the builder.
func (_c *PluginKVCreate) Mutation() *PluginKVMutation {
	return _c.mutation
}

// Save creates the PluginKV in the database.
func (_c *PluginKVCreate) Save(ctx context.Context) (*PluginKV, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PluginKVCreate) SaveX(ctx context.Context) *PluginKV {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginKVCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginKVCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PluginKVCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pluginkv.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := pluginkv.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PluginKVCreate) check() error {
	if _, ok := _c.mutation.PluginID(); !ok {
		return &ValidationError{Name: "plugin_id", err: errors.New(`ent: missing required field "PluginKV.plugin_id"`)}
	}
	if v, ok := _c.mutation.PluginID(); ok {
		if err := pluginkv.PluginIDValidator(v); err != nil {
			return &ValidationError{Name: "plugin_id", err: fmt.Errorf(`ent: validator failed for field "PluginKV.plugin_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "PluginKV.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := pluginkv.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "PluginKV.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "PluginKV.value"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PluginKV.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PluginKV.updated_at"`)}
	}
	return nil
}

func (_c *PluginKVCreate) sqlSave(ctx context.Context) (*PluginKV, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PluginKVCreate) createSpec() (*PluginKV, *sqlgraph.CreateSpec) {
	var (
		_node = &PluginKV{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pluginkv.Table, sqlgraph.NewFieldSpec(pluginkv.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.PluginID(); ok {
		_spec.SetField(pluginkv.FieldPluginID, field.TypeString, value)
		_node.PluginID = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(pluginkv.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(pluginkv.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pluginkv.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(pluginkv.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PluginKV.Create().
//		SetPluginID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PluginKVUpsert) {
//			SetPluginID(v+v).
//		}).
//		Exec(ctx)
func (_c *PluginKVCreate) OnConflict(opts ...sql.ConflictOption) *PluginKVUpsertOne {
	_c.conflict = opts
	return &PluginKVUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PluginKV.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PluginKVCreate) OnConflictColumns(columns ...string) *PluginKVUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PluginKVUpsertOne{
		create: _c,
	}
}

type (
	// PluginKVUpsertOne is the builder for "upsert"-ing
	//  one PluginKV node.
	PluginKVUpsertOne struct {
		create *PluginKVCreate
	}

	// PluginKVUpsert is the "OnConflict" setter.
	PluginKVUpsert struct {
		*sql.UpdateSet
	}
)

// SetPluginID sets the "plugin_id" field.
func (u *PluginKVUpsert) SetPluginID(v string) *PluginKVUpsert {
	u.Set(pluginkv.FieldPluginID, v)
	return u
}

// UpdatePluginID sets the "plugin_id" field to the value that was provided on create.
func (u *PluginKVUpsert) UpdatePluginID() *PluginKVUpsert {
	u.SetExcluded(pluginkv.FieldPluginID)
	return u
}

// SetKey sets the "key" field.
func (u *PluginKVUpsert) SetKey(v string) *PluginKVUpsert {
	u.Set(pluginkv.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *PluginKVUpsert) UpdateKey() *PluginKVUpsert {
	u.SetExcluded(pluginkv.FieldKey)
	return u
}

// SetValue sets the "value" field.
func (u *PluginKVUpsert) SetValue(v string) *PluginKVUpsert {
	u.Set(pluginkv.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *PluginKVUpsert) UpdateValue() *PluginKVUpsert {
	u.SetExcluded(pluginkv.FieldValue)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PluginKVUpsert) SetUpdatedAt(v time.Time) *PluginKVUpsert {
	u.Set(pluginkv.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PluginKVUpsert) UpdateUpdatedAt() *PluginKVUpsert {
	u.SetExcluded(pluginkv.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PluginKV.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PluginKVUpsertOne) UpdateNewValues() *PluginKVUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(pluginkv.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PluginKV.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PluginKVUpsertOne) Ignore() *PluginKVUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PluginKVUpsertOne) DoNothing() *PluginKVUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PluginKVCreate.OnConflict
// documentation for more info.
func (u *PluginKVUpsertOne) Update(set func(*PluginKVUpsert)) *PluginKVUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PluginKVUpsert{UpdateSet: update})
	}))
	return u
}

// SetPluginID sets the "plugin_id" field.
func (u *PluginKVUpsertOne) SetPluginID(v string) *PluginKVUpsertOne {
	return u.Update(func(s *PluginKVUpsert) {
		s.SetPluginID(v)
	})
}

// UpdatePluginID sets the "plugin_id" field to the value that was provided on create.
func (u *PluginKVUpsertOne) UpdatePluginID() *PluginKVUpsertOne {
	return u.Update(func(s *PluginKVUpsert) {
		s.UpdatePluginID()
	})
}

// SetKey sets the "key" field.
func (u *PluginKVUpsertOne) SetKey(v string) *PluginKVUpsertOne {
	return u.Update(func(s *PluginKVUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *PluginKVUpsertOne) UpdateKey() *PluginKVUpsertOne {
	return u.Update(func(s *PluginKVUpsert) {
		s.UpdateKey()
	})
}

// SetValue sets the "value" field.
func (u *PluginKVUpsertOne) SetValue(v string) *PluginKVUpsertOne {
	return u.Update(func(s *PluginKVUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *PluginKVUpsertOne) UpdateValue() *PluginKVUpsertOne {
	return u.Update(func(s *PluginKVUpsert) {
		s.UpdateValue()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PluginKVUpsertOne) SetUpdatedAt(v time.Time) *PluginKVUpsertOne {
	return u.Update(func(s *PluginKVUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PluginKVUpsertOne) UpdateUpdatedAt() *PluginKVUpsertOne {
	return u.Update(func(s *PluginKVUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PluginKVUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PluginKVCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PluginKVUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PluginKVUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PluginKVUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PluginKVCreateBulk is the builder for creating many PluginKV entities in bulk.
type PluginKVCreateBulk struct {
	config
	err      error
	builders []*PluginKVCreate
	conflict []sql.ConflictOption
}

// Save creates the PluginKV entities in the database.
func (_c *PluginKVCreateBulk) Save(ctx context.Context) ([]*PluginKV, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PluginKV, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PluginKVMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PluginKVCreateBulk) SaveX(ctx context.Context) []*PluginKV {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginKVCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginKVCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PluginKV.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PluginKVUpsert) {
//			SetPluginID(v+v).
//		}).
//		Exec(ctx)
func (_c *PluginKVCreateBulk) OnConflict(opts ...sql.ConflictOption) *PluginKVUpsertBulk {
	_c.conflict = opts
	return &PluginKVUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PluginKV.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PluginKVCreateBulk) OnConflictColumns(columns ...string) *PluginKVUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PluginKVUpsertBulk{
		create: _c,
	}
}

// PluginKVUpsertBulk is the builder for "upsert"-ing
// a bulk of PluginKV nodes.
type PluginKVUpsertBulk struct {
	create *PluginKVCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PluginKV.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PluginKVUpsertBulk) UpdateNewValues() *PluginKVUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(pluginkv.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PluginKV.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PluginKVUpsertBulk) Ignore() *PluginKVUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PluginKVUpsertBulk) DoNothing() *PluginKVUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PluginKVCreateBulk.OnConflict
// documentation for more info.
func (u *PluginKVUpsertBulk) Update(set func(*PluginKVUpsert)) *PluginKVUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PluginKVUpsert{UpdateSet: update})
	}))
	return u
}

// SetPluginID sets the "plugin_id" field.
func (u *PluginKVUpsertBulk) SetPluginID(v string) *PluginKVUpsertBulk {
	return u.Update(func(s *PluginKVUpsert) {
		s.SetPluginID(v)
	})
}

// UpdatePluginID sets the "plugin_id" field to the value that was provided on create.
func (u *PluginKVUpsertBulk) UpdatePluginID() *PluginKVUpsertBulk {
	return u.Update(func(s *PluginKVUpsert) {
		s.UpdatePluginID()
	})
}

// SetKey sets the "key" field.
func (u *PluginKVUpsertBulk) SetKey(v string) *PluginKVUpsertBulk {
	return u.Update(func(s *PluginKVUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *PluginKVUpsertBulk) UpdateKey() *PluginKVUpsertBulk {
	return u.Update(func(s *PluginKVUpsert) {
		s.UpdateKey()
	})
}

// SetValue sets the "value" field.
func (u *PluginKVUpsertBulk) SetValue(v string) *PluginKVUpsertBulk {
	return u.Update(func(s *PluginKVUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *PluginKVUpsertBulk) UpdateValue() *PluginKVUpsertBulk {
	return u.Update(func(s *PluginKVUpsert) {
		s.UpdateValue()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PluginKVUpsertBulk) SetUpdatedAt(v time.Time) *PluginKVUpsertBulk {
	return u.Update(func(s *PluginKVUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PluginKVUpsertBulk) UpdateUpdatedAt() *PluginKVUpsertBulk {
	return u.Update(func(s *PluginKVUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PluginKVUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PluginKVCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PluginKVCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PluginKVUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
