// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/pluginstate"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PluginStateUpdate is the builder for updating PluginState entities.
type PluginStateUpdate struct {
	config
	hooks    []Hook
	mutation *PluginStateMutation
}

// Where appends a list predicates to the PluginStateUpdate builder.
func (_u *PluginStateUpdate) Where(ps ...predicate.PluginState) *PluginStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PluginStateUpdate) SetEnabled(v bool) *PluginStateUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PluginStateUpdate) SetNillableEnabled(v *bool) *PluginStateUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *PluginStateUpdate) SetUpdatedBy(v string) *PluginStateUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *PluginStateUpdate) SetNillableUpdatedBy(v *string) *PluginStateUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PluginStateUpdate) SetUpdatedAt(v time.Time) *PluginStateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PluginStateMutation object of the builder.
func (_u *PluginStateUpdate) Mutation() *PluginStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PluginStateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PluginStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PluginStateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pluginstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *PluginStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(pluginstate.Table, pluginstate.Columns, sqlgraph.NewFieldSpec(pluginstate.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(pluginstate.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(pluginstate.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pluginstate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pluginstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PluginStateUpdateOne is the builder for updating a single PluginState entity.
type PluginStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PluginStateMutation
}

// SetEnabled sets the "enabled" field.
func (_u *PluginStateUpdateOne) SetEnabled(v bool) *PluginStateUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PluginStateUpdateOne) SetNillableEnabled(v *bool) *PluginStateUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *PluginStateUpdateOne) SetUpdatedBy(v string) *PluginStateUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *PluginStateUpdateOne) SetNillableUpdatedBy(v *string) *PluginStateUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PluginStateUpdateOne) SetUpdatedAt(v time.Time) *PluginStateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PluginStateMutation object of the builder.
func (_u *PluginStateUpdateOne) Mutation() *PluginStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the PluginStateUpdate builder.
func (_u *PluginStateUpdateOne) Where(ps ...predicate.PluginState) *PluginStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PluginStateUpdateOne) Select(field string, fields ...string) *PluginStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PluginState entity.
func (_u *PluginStateUpdateOne) Save(ctx context.Context) (*PluginState, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginStateUpdateOne) SaveX(ctx context.Context) *PluginState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PluginStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PluginStateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := pluginstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *PluginStateUpdateOne) sqlSave(ctx context.Context) (_node *PluginState, err error) {
	_spec := sqlgraph.NewUpdateSpec(pluginstate.Table, pluginstate.Columns, sqlgraph.NewFieldSpec(pluginstate.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PluginState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pluginstate.FieldID)
		for _, f := range fields {
			if !pluginstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pluginstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(pluginstate.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(pluginstate.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pluginstate.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PluginState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pluginstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
