// Code generated by ent, DO NOT EDIT.

package plugininstallation

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the plugininstallation type in the database.
	Label = "plugin_installation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldManifest holds the string denoting the manifest field in the database.
	FieldManifest = "manifest"
	// FieldInstallPath holds the string denoting the install_path field in the database.
	FieldInstallPath = "install_path"
	// FieldChecksum holds the string denoting the checksum field in the database.
	FieldChecksum = "checksum"
	// FieldConfig holds the string denoting the config field in the database.
	FieldConfig = "config"
	// FieldInstalledBy holds the string denoting the installed_by field in the database.
	FieldInstalledBy = "installed_by"
	// FieldInstalledAt holds the string denoting the installed_at field in the database.
	FieldInstalledAt = "installed_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the plugininstallation in the database.
	Table = "plugin_installations"
)

// Columns holds all SQL columns for plugininstallation fields.
var Columns = []string{
	FieldID,
	FieldVersion,
	FieldManifest,
	FieldInstallPath,
	FieldChecksum,
	FieldConfig,
	FieldInstalledBy,
	FieldInstalledAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(string) error
	// InstallPathValidator is a validator for the "install_path" field. It is called by the builders before save.
	InstallPathValidator func(string) error
	// ChecksumValidator is a validator for the "checksum" field. It is called by the builders before save.
	ChecksumValidator func(string) error
	// DefaultInstalledBy holds the default value on creation for the "installed_by" field.
	DefaultInstalledBy string
	// DefaultInstalledAt holds the default value on creation for the "installed_at" field.
	DefaultInstalledAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the PluginInstallation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByInstallPath orders the results by the install_path field.
func ByInstallPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstallPath, opts...).ToFunc()
}

// ByChecksum orders the results by the checksum field.
func ByChecksum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChecksum, opts...).ToFunc()
}

// ByInstalledBy orders the results by the installed_by field.
func ByInstalledBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstalledBy, opts...).ToFunc()
}

// ByInstalledAt orders the results by the installed_at field.
func ByInstalledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstalledAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
