// Code generated by ent, DO NOT EDIT.

package plugininstallation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldContainsFold(FieldID, id))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldEQ(FieldVersion, v))
}

// InstallPath applies equality check predicate on the "install_path" field. It's identical to InstallPathEQ.
func InstallPath(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldEQ(FieldInstallPath, v))
}

// Checksum applies equality check predicate on the "checksum" field. It's identical to ChecksumEQ.
func Checksum(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldEQ(FieldChecksum, v))
}

// InstalledBy applies equality check predicate on the "installed_by" field. It's identical to InstalledByEQ.
func InstalledBy(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldEQ(FieldInstalledBy, v))
}

// InstalledAt applies equality check predicate on the "installed_at" field. It's identical to InstalledAtEQ.
func InstalledAt(v time.Time) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldEQ(FieldInstalledAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldEQ(FieldUpdatedAt, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldContainsFold(FieldVersion, v))
}

// InstallPathEQ applies the EQ predicate on the "install_path" field.
func InstallPathEQ(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldEQ(FieldInstallPath, v))
}

// InstallPathNEQ applies the NEQ predicate on the "install_path" field.
func InstallPathNEQ(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldNEQ(FieldInstallPath, v))
}

// InstallPathIn applies the In predicate on the "install_path" field.
func InstallPathIn(vs ...string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldIn(FieldInstallPath, vs...))
}

// InstallPathNotIn applies the NotIn predicate on the "install_path" field.
func InstallPathNotIn(vs ...string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldNotIn(FieldInstallPath, vs...))
}

// InstallPathGT applies the GT predicate on the "install_path" field.
func InstallPathGT(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldGT(FieldInstallPath, v))
}

// InstallPathGTE applies the GTE predicate on the "install_path" field.
func InstallPathGTE(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldGTE(FieldInstallPath, v))
}

// InstallPathLT applies the LT predicate on the "install_path" field.
func InstallPathLT(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldLT(FieldInstallPath, v))
}

// InstallPathLTE applies the LTE predicate on the "install_path" field.
func InstallPathLTE(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldLTE(FieldInstallPath, v))
}

// InstallPathContains applies the Contains predicate on the "install_path" field.
func InstallPathContains(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldContains(FieldInstallPath, v))
}

// InstallPathHasPrefix applies the HasPrefix predicate on the "install_path" field.
func InstallPathHasPrefix(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldHasPrefix(FieldInstallPath, v))
}

// InstallPathHasSuffix applies the HasSuffix predicate on the "install_path" field.
func InstallPathHasSuffix(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldHasSuffix(FieldInstallPath, v))
}

// InstallPathEqualFold applies the EqualFold predicate on the "install_path" field.
func InstallPathEqualFold(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldEqualFold(FieldInstallPath, v))
}

// InstallPathContainsFold applies the ContainsFold predicate on the "install_path" field.
func InstallPathContainsFold(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldContainsFold(FieldInstallPath, v))
}

// ChecksumEQ applies the EQ predicate on the "checksum" field.
func ChecksumEQ(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldEQ(FieldChecksum, v))
}

// ChecksumNEQ applies the NEQ predicate on the "checksum" field.
func ChecksumNEQ(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldNEQ(FieldChecksum, v))
}

// ChecksumIn applies the In predicate on the "checksum" field.
func ChecksumIn(vs ...string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldIn(FieldChecksum, vs...))
}

// ChecksumNotIn applies the NotIn predicate on the "checksum" field.
func ChecksumNotIn(vs ...string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldNotIn(FieldChecksum, vs...))
}

// ChecksumGT applies the GT predicate on the "checksum" field.
func ChecksumGT(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldGT(FieldChecksum, v))
}

// ChecksumGTE applies the GTE predicate on the "checksum" field.
func ChecksumGTE(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldGTE(FieldChecksum, v))
}

// ChecksumLT applies the LT predicate on the "checksum" field.
func ChecksumLT(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldLT(FieldChecksum, v))
}

// ChecksumLTE applies the LTE predicate on the "checksum" field.
func ChecksumLTE(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldLTE(FieldChecksum, v))
}

// ChecksumContains applies the Contains predicate on the "checksum" field.
func ChecksumContains(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldContains(FieldChecksum, v))
}

// ChecksumHasPrefix applies the HasPrefix predicate on the "checksum" field.
func ChecksumHasPrefix(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldHasPrefix(FieldChecksum, v))
}

// ChecksumHasSuffix applies the HasSuffix predicate on the "checksum" field.
func ChecksumHasSuffix(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldHasSuffix(FieldChecksum, v))
}

// ChecksumEqualFold applies the EqualFold predicate on the "checksum" field.
func ChecksumEqualFold(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldEqualFold(FieldChecksum, v))
}

// ChecksumContainsFold applies the ContainsFold predicate on the "checksum" field.
func ChecksumContainsFold(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldContainsFold(FieldChecksum, v))
}

// ConfigIsNil applies the IsNil predicate on the "config" field.
func ConfigIsNil() predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldIsNull(FieldConfig))
}

// ConfigNotNil applies the NotNil predicate on the "config" field.
func ConfigNotNil() predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldNotNull(FieldConfig))
}

// InstalledByEQ applies the EQ predicate on the "installed_by" field.
func InstalledByEQ(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldEQ(FieldInstalledBy, v))
}

// InstalledByNEQ applies the NEQ predicate on the "installed_by" field.
func InstalledByNEQ(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldNEQ(FieldInstalledBy, v))
}

// InstalledByIn applies the In predicate on the "installed_by" field.
func InstalledByIn(vs ...string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldIn(FieldInstalledBy, vs...))
}

// InstalledByNotIn applies the NotIn predicate on the "installed_by" field.
func InstalledByNotIn(vs ...string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldNotIn(FieldInstalledBy, vs...))
}

// InstalledByGT applies the GT predicate on the "installed_by" field.
func InstalledByGT(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldGT(FieldInstalledBy, v))
}

// InstalledByGTE applies the GTE predicate on the "installed_by" field.
func InstalledByGTE(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldGTE(FieldInstalledBy, v))
}

// InstalledByLT applies the LT predicate on the "installed_by" field.
func InstalledByLT(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldLT(FieldInstalledBy, v))
}

// InstalledByLTE applies the LTE predicate on the "installed_by" field.
func InstalledByLTE(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldLTE(FieldInstalledBy, v))
}

// InstalledByContains applies the Contains predicate on the "installed_by" field.
func InstalledByContains(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldContains(FieldInstalledBy, v))
}

// InstalledByHasPrefix applies the HasPrefix predicate on the "installed_by" field.
func InstalledByHasPrefix(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldHasPrefix(FieldInstalledBy, v))
}

// InstalledByHasSuffix applies the HasSuffix predicate on the "installed_by" field.
func InstalledByHasSuffix(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldHasSuffix(FieldInstalledBy, v))
}

// InstalledByEqualFold applies the EqualFold predicate on the "installed_by" field.
func InstalledByEqualFold(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldEqualFold(FieldInstalledBy, v))
}

// InstalledByContainsFold applies the ContainsFold predicate on the "installed_by" field.
func InstalledByContainsFold(v string) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldContainsFold(FieldInstalledBy, v))
}

// InstalledAtEQ applies the EQ predicate on the "installed_at" field.
func InstalledAtEQ(v time.Time) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldEQ(FieldInstalledAt, v))
}

// InstalledAtNEQ applies the NEQ predicate on the "installed_at" field.
func InstalledAtNEQ(v time.Time) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldNEQ(FieldInstalledAt, v))
}

// InstalledAtIn applies the In predicate on the "installed_at" field.
func InstalledAtIn(vs ...time.Time) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldIn(FieldInstalledAt, vs...))
}

// InstalledAtNotIn applies the NotIn predicate on the "installed_at" field.
func InstalledAtNotIn(vs ...time.Time) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldNotIn(FieldInstalledAt, vs...))
}

// InstalledAtGT applies the GT predicate on the "installed_at" field.
func InstalledAtGT(v time.Time) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldGT(FieldInstalledAt, v))
}

// InstalledAtGTE applies the GTE predicate on the "installed_at" field.
func InstalledAtGTE(v time.Time) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldGTE(FieldInstalledAt, v))
}

// InstalledAtLT applies the LT predicate on the "installed_at" field.
func InstalledAtLT(v time.Time) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldLT(FieldInstalledAt, v))
}

// InstalledAtLTE applies the LTE predicate on the "installed_at" field.
func InstalledAtLTE(v time.Time) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldLTE(FieldInstalledAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PluginInstallation) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PluginInstallation) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PluginInstallation) predicate.PluginInstallation {
	return predicate.PluginInstallation(sql.NotPredicates(p))
}
